import { contextBridge, ipcRenderer } from 'electron';
import {
  IPC,
  type AccountGroupSummary,
  type AdminResetPasswordInput,
  type AdminResetPasswordResult,
  type BalanceSheetResult,
  type ChangePasswordInput,
  type CompanySummary,
  type CompanyUserSummary,
  type CreateCompanyInput,
  type CreateCompanyResult,
  type CreateLedgerInput,
  type CreatePartyInput,
  type CreateRoleInput,
  type CreateItemInput,
  type CreateUnitOfMeasureInput,
  type CreateWarehouseInput,
  type ItemBatchSummary,
  type PostStockAdjustmentInput,
  type RecordOpeningStockInput,
  type StockMovementSummary,
  type StockPositionQuery,
  type StockPositionRow,
  type TransferStockInput,
  type CreatePurchaseInvoiceInput,
  type CreatePurchaseOrderInput,
  type CreateSalesInvoiceInput,
  type CreateSalesOrderInput,
  type CreateVoucherInput,
  type InvoiceSummary,
  type InviteUserInput,
  type InviteUserResult,
  type IpcResult,
  type ItemSummary,
  type LicenseStatus,
  type LedgerAccountSummary,
  type LoginInput,
  type LoginResult,
  type MsmeAgeingRow,
  type OrderSummary,
  type OutstandingInvoiceRow,
  type PartyOutstandingRow,
  type PartySummary,
  type PermissionSummary,
  type ProfitAndLossInput,
  type ProfitAndLossResult,
  type PurchaseInvoiceSummary,
  type RecordPurchasePaymentInput,
  type RecordSalesReceiptInput,
  type ResetPasswordInput,
  type RestoreResult,
  type RoleSummary,
  type RoleWithPermissionsSummary,
  type SessionInfo,
  type ThemePreference,
  type UnitOfMeasureSummary,
  type UpdateRolePermissionsInput,
  type TrialBalanceResult,
  type VoucherSummary,
  type WarehouseSummary,
} from '../shared/ipc';

const api = {
  listCompanies: (): Promise<IpcResult<CompanySummary[]>> => ipcRenderer.invoke(IPC.LIST_COMPANIES),
  createCompany: (input: CreateCompanyInput): Promise<IpcResult<CreateCompanyResult>> =>
    ipcRenderer.invoke(IPC.CREATE_COMPANY, input),
  listCompanyUsers: (): Promise<IpcResult<CompanyUserSummary[]>> => ipcRenderer.invoke(IPC.LIST_COMPANY_USERS),
  inviteUser: (input: InviteUserInput): Promise<IpcResult<InviteUserResult>> => ipcRenderer.invoke(IPC.INVITE_USER, input),
  listRoles: (): Promise<IpcResult<RoleSummary[]>> => ipcRenderer.invoke(IPC.LIST_ROLES),
  login: (input: LoginInput): Promise<IpcResult<LoginResult>> => ipcRenderer.invoke(IPC.LOGIN, input),
  changePassword: (input: ChangePasswordInput): Promise<IpcResult<SessionInfo>> =>
    ipcRenderer.invoke(IPC.CHANGE_PASSWORD, input),
  resetPassword: (input: ResetPasswordInput): Promise<IpcResult<SessionInfo>> =>
    ipcRenderer.invoke(IPC.RESET_PASSWORD, input),
  adminResetPassword: (input: AdminResetPasswordInput): Promise<IpcResult<AdminResetPasswordResult>> =>
    ipcRenderer.invoke(IPC.ADMIN_RESET_PASSWORD, input),
  logout: (): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.LOGOUT),
  getSession: (): Promise<IpcResult<SessionInfo | null>> => ipcRenderer.invoke(IPC.GET_SESSION),
  listAccountGroups: (): Promise<IpcResult<AccountGroupSummary[]>> => ipcRenderer.invoke(IPC.LIST_ACCOUNT_GROUPS),
  listLedgers: (): Promise<IpcResult<LedgerAccountSummary[]>> => ipcRenderer.invoke(IPC.LIST_LEDGERS),
  createLedger: (input: CreateLedgerInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_LEDGER, input),
  createVoucher: (input: CreateVoucherInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_VOUCHER, input),
  listVouchers: (): Promise<IpcResult<VoucherSummary[]>> => ipcRenderer.invoke(IPC.LIST_VOUCHERS),
  cancelVoucher: (voucherId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CANCEL_VOUCHER, voucherId),
  getTrialBalance: (): Promise<IpcResult<TrialBalanceResult>> => ipcRenderer.invoke(IPC.GET_TRIAL_BALANCE),
  getProfitAndLoss: (input: ProfitAndLossInput): Promise<IpcResult<ProfitAndLossResult>> =>
    ipcRenderer.invoke(IPC.GET_PROFIT_AND_LOSS, input),
  getBalanceSheet: (asOfDate: string): Promise<IpcResult<BalanceSheetResult>> =>
    ipcRenderer.invoke(IPC.GET_BALANCE_SHEET, asOfDate),
  createParty: (input: CreatePartyInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PARTY, input),
  listParties: (): Promise<IpcResult<PartySummary[]>> => ipcRenderer.invoke(IPC.LIST_PARTIES),
  createSalesInvoice: (input: CreateSalesInvoiceInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_SALES_INVOICE, input),
  listSalesInvoices: (): Promise<IpcResult<InvoiceSummary[]>> => ipcRenderer.invoke(IPC.LIST_SALES_INVOICES),
  cancelSalesInvoice: (invoiceId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CANCEL_SALES_INVOICE, invoiceId),
  createPurchaseInvoice: (input: CreatePurchaseInvoiceInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PURCHASE_INVOICE, input),
  listPurchaseInvoices: (): Promise<IpcResult<PurchaseInvoiceSummary[]>> => ipcRenderer.invoke(IPC.LIST_PURCHASE_INVOICES),
  cancelPurchaseInvoice: (invoiceId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CANCEL_PURCHASE_INVOICE, invoiceId),
  createSalesOrder: (input: CreateSalesOrderInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_SALES_ORDER, input),
  listSalesOrders: (): Promise<IpcResult<OrderSummary[]>> => ipcRenderer.invoke(IPC.LIST_SALES_ORDERS),
  confirmSalesOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CONFIRM_SALES_ORDER, orderId),
  cancelSalesOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CANCEL_SALES_ORDER, orderId),
  convertSalesOrder: (orderId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CONVERT_SALES_ORDER, orderId),
  createPurchaseOrder: (input: CreatePurchaseOrderInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PURCHASE_ORDER, input),
  listPurchaseOrders: (): Promise<IpcResult<OrderSummary[]>> => ipcRenderer.invoke(IPC.LIST_PURCHASE_ORDERS),
  confirmPurchaseOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CONFIRM_PURCHASE_ORDER, orderId),
  cancelPurchaseOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CANCEL_PURCHASE_ORDER, orderId),
  convertPurchaseOrder: (orderId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CONVERT_PURCHASE_ORDER, orderId),
  listReceivables: (): Promise<IpcResult<PartyOutstandingRow[]>> => ipcRenderer.invoke(IPC.LIST_RECEIVABLES),
  listPayables: (): Promise<IpcResult<PartyOutstandingRow[]>> => ipcRenderer.invoke(IPC.LIST_PAYABLES),
  listMsmeAgeing: (asOfDate: string): Promise<IpcResult<MsmeAgeingRow[]>> => ipcRenderer.invoke(IPC.LIST_MSME_AGEING, asOfDate),
  listOutstandingSalesInvoices: (partyId: string): Promise<IpcResult<OutstandingInvoiceRow[]>> => ipcRenderer.invoke(IPC.LIST_OUTSTANDING_SALES_INVOICES, partyId),
  listOutstandingPurchaseInvoices: (partyId: string): Promise<IpcResult<OutstandingInvoiceRow[]>> => ipcRenderer.invoke(IPC.LIST_OUTSTANDING_PURCHASE_INVOICES, partyId),
  recordSalesReceipt: (input: RecordSalesReceiptInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RECORD_SALES_RECEIPT, input),
  recordPurchasePayment: (input: RecordPurchasePaymentInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RECORD_PURCHASE_PAYMENT, input),
  getThemePreference: (): Promise<IpcResult<ThemePreference>> => ipcRenderer.invoke(IPC.GET_THEME_PREFERENCE),
  setThemePreference: (theme: ThemePreference): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.SET_THEME_PREFERENCE, theme),
  backupCompany: (): Promise<IpcResult<string | null>> => ipcRenderer.invoke(IPC.BACKUP_COMPANY),
  restoreCompany: (): Promise<IpcResult<RestoreResult>> => ipcRenderer.invoke(IPC.RESTORE_COMPANY),
  getLicenseStatus: (): Promise<IpcResult<LicenseStatus>> => ipcRenderer.invoke(IPC.GET_LICENSE_STATUS),
  activateLicense: (): Promise<IpcResult<LicenseStatus>> => ipcRenderer.invoke(IPC.ACTIVATE_LICENSE),
  listAllPermissions: (): Promise<IpcResult<PermissionSummary[]>> => ipcRenderer.invoke(IPC.LIST_ALL_PERMISSIONS),
  listRolesWithPermissions: (): Promise<IpcResult<RoleWithPermissionsSummary[]>> => ipcRenderer.invoke(IPC.LIST_ROLES_WITH_PERMISSIONS),
  createRole: (input: CreateRoleInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_ROLE, input),
  updateRolePermissions: (input: UpdateRolePermissionsInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_ROLE_PERMISSIONS, input),
  createUnitOfMeasure: (input: CreateUnitOfMeasureInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_UNIT_OF_MEASURE, input),
  listUnitsOfMeasure: (): Promise<IpcResult<UnitOfMeasureSummary[]>> => ipcRenderer.invoke(IPC.LIST_UNITS_OF_MEASURE),
  createWarehouse: (input: CreateWarehouseInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_WAREHOUSE, input),
  listWarehouses: (): Promise<IpcResult<WarehouseSummary[]>> => ipcRenderer.invoke(IPC.LIST_WAREHOUSES),
  createItem: (input: CreateItemInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_ITEM, input),
  listItems: (): Promise<IpcResult<ItemSummary[]>> => ipcRenderer.invoke(IPC.LIST_ITEMS),
  listBatchesForItem: (itemId: string): Promise<IpcResult<ItemBatchSummary[]>> => ipcRenderer.invoke(IPC.LIST_BATCHES_FOR_ITEM, itemId),
  recordOpeningStock: (input: RecordOpeningStockInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RECORD_OPENING_STOCK, input),
  postStockAdjustment: (input: PostStockAdjustmentInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.POST_STOCK_ADJUSTMENT, input),
  transferStock: (input: TransferStockInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.TRANSFER_STOCK, input),
  listStockMovements: (): Promise<IpcResult<StockMovementSummary[]>> => ipcRenderer.invoke(IPC.LIST_STOCK_MOVEMENTS),
  getStockPosition: (query: StockPositionQuery): Promise<IpcResult<StockPositionRow[]>> => ipcRenderer.invoke(IPC.GET_STOCK_POSITION, query),
};

export type MhtsApi = typeof api;

contextBridge.exposeInMainWorld('mhts', api);
