import { contextBridge, ipcRenderer } from 'electron';
import {
  IPC,
  type AccountGroupSummary,
  type AdminResetPasswordInput,
  type AdminResetPasswordResult,
  type AuditChainVerificationResult,
  type BalanceSheetResult,
  type ChangePasswordInput,
  type CompanySummary,
  type CompanyUserSummary,
  type CreateCompanyInput,
  type CreateCompanyResult,
  type CreateLedgerInput,
  type CreatePartyInput,
  type CreateRoleInput,
  type CreateItemInput,
  type CreateUnitOfMeasureInput,
  type CreateWarehouseInput,
  type ItemBatchSummary,
  type PostStockAdjustmentInput,
  type RecordOpeningStockInput,
  type StockMovementSummary,
  type StockPositionQuery,
  type StockPositionRow,
  type TransferStockInput,
  type CreatePurchaseInvoiceInput,
  type CreatePurchaseOrderInput,
  type CreateSalesInvoiceInput,
  type CreateSalesOrderInput,
  type CreateVoucherInput,
  type InvoiceSummary,
  type InviteUserInput,
  type InviteUserResult,
  type IpcResult,
  type ItemSummary,
  type LicenseStatus,
  type TrialStatus,
  type LedgerAccountSummary,
  type LoginInput,
  type LoginResult,
  type MsmeAgeingRow,
  type OrderSummary,
  type OutstandingInvoiceRow,
  type PartyOutstandingRow,
  type PartySummary,
  type PermissionSummary,
  type ProfitAndLossInput,
  type ProfitAndLossResult,
  type PurchaseInvoiceSummary,
  type RecordPurchasePaymentInput,
  type RecordSalesReceiptInput,
  type ResetPasswordInput,
  type RestoreResult,
  type RoleSummary,
  type RoleWithPermissionsSummary,
  type SessionInfo,
  type ThemePreference,
  type UnitOfMeasureSummary,
  type UpdateRolePermissionsInput,
  type TrialBalanceResult,
  type VoucherSummary,
  type WarehouseSummary,
  type CreateOrUpdateGstRateInput,
  type GstRatePreviewInput,
  type GstRatePreviewResult,
  type GstRateSummary,
  type GstRateVersion,
  type GstSummaryInput,
  type GstSummaryResult,
  type GstReturnPeriodInput,
  type GstFinancialYearInput,
  type Gstr1Result,
  type Gstr3bResult,
  type Gstr9Result,
  type Gstr9cResult,
  type ExportCsvInput,
  type BankAccountSummary,
  type BankReconciliationStatement,
  type CreateBankAccountInput,
  type GetReconciliationStatementInput,
  type ImportStatementFileInput,
  type ImportStatementResult,
  type InstrumentStatus,
  type ListReconcilableLinesInput,
  type MarkReconciledInput,
  type PaymentInstrumentSummary,
  type ReconcilableLineRow,
  type RecordBankVoucherInput,
  type ResolveStatementLineMatchInput,
  type StatementImportSummary,
  type StatementLineSummary,
  type StatementPreview,
  type UpdateInstrumentStatusInput,
  type EmployeeSummary,
  type CreateEmployeeInput,
  type ExpenseClaimSummary,
  type CreateExpenseClaimInput,
  type RejectExpenseClaimInput,
  type ReimburseExpenseClaimInput,
  type OutstandingReimbursementRow,
  type DocumentSummary,
  type UploadDocumentInput,
  type ListDocumentsForEntityInput,
  type DownloadDocumentResult,
  type SearchDocumentsInput,
  type EmployeePayrollProfileSummary,
  type UpdateEmployeePayrollProfileInput,
  type SalaryComponentDefinitionInput,
  type SalaryComponentDefinitionSummary,
  type AssignSalaryStructureInput,
  type SalaryStructureSummary,
  type CompanyPayrollSettingsSummary,
  type UpdateCompanyPayrollSettingsInput,
  type CreateOrUpdatePayrollRuleInput,
  type PayrollRuleVersionSummary,
  type LeaveTypeInput,
  type LeaveTypeSummary,
  type ApplyLeaveInput,
  type LeaveApplicationSummary,
  type RejectLeaveInput,
  type LeaveBalanceSummary,
  type MarkAttendanceInput,
  type ListAttendanceForEmployeeInput,
  type AttendanceRecordSummary,
  type CreatePayrollRunInput,
  type OverridePayslipTdsInput,
  type PayrollRunSummary,
  type DisbursePayslipInput,
  type RunGratuityProvisioningInput,
  type RecordSeparationInput,
  type GratuityRecordSummary,
  type SettleGratuityInput,
  type CostCentreSummary,
  type CreateCostCentreInput,
  type UpdateCostCentreInput,
  type CostCentreReportInput,
  type CostCentreSummaryRow,
  type CreateBudgetInput,
  type BudgetSummary,
  type UpdateBudgetLineInput,
  type BudgetVsActualResult,
  type AssetClassSummary,
  type CreateAssetClassInput,
  type FixedAssetSummary,
  type AcquireFixedAssetInput,
  type AssetDepreciationEntrySummary,
  type DisposeFixedAssetInput,
  type DepreciationPreviewLine,
  type RunDepreciationInput,
  type PostDepreciationResult,
  type CreateOrUpdateFixedAssetRateInput,
  type FixedAssetRateVersionSummary,
  type BranchSummary,
  type CreateBranchInput,
  type UpdateBranchInput,
  type RecordInterBranchTransferInput,
  type BranchProfitAndLossRow,
  type BranchReportInput,
  type BranchBalanceSheetResult,
  type ExchangeRateVersionSummary,
  type SetExchangeRateInput,
  type FxRevaluationPreviewResult,
  type RunFxRevaluationInput,
  type FxRevaluationRunResult,
  type BillOfMaterialSummary,
  type CreateBillOfMaterialInput,
  type PostManufacturingJournalInput,
  type ManufacturingJournalSummary,
  type ManufacturingJournalMovementSummary,
  type CompanyLetterheadProfile,
  type UpdateCompanyLetterheadProfileInput,
  type PickedLogoFile,
  type UploadCompanyLogoInput,
  type PrintDocumentResult,
  type PayslipPrintListItem,
  type UpdateBusinessPartyAddressInput,
  type TemplateFamily,
  type PrintTemplateLayoutSummary,
  type SaveTemplateLayoutInput,
  type TemplatePreviewData,
  type TemplateFieldCatalogEntry,
  type UpdateStatus,
  UPDATE_STATUS_EVENT,
} from '../shared/ipc';

const api = {
  listCompanies: (): Promise<IpcResult<CompanySummary[]>> => ipcRenderer.invoke(IPC.LIST_COMPANIES),
  createCompany: (input: CreateCompanyInput): Promise<IpcResult<CreateCompanyResult>> =>
    ipcRenderer.invoke(IPC.CREATE_COMPANY, input),
  listCompanyUsers: (): Promise<IpcResult<CompanyUserSummary[]>> => ipcRenderer.invoke(IPC.LIST_COMPANY_USERS),
  inviteUser: (input: InviteUserInput): Promise<IpcResult<InviteUserResult>> => ipcRenderer.invoke(IPC.INVITE_USER, input),
  listRoles: (): Promise<IpcResult<RoleSummary[]>> => ipcRenderer.invoke(IPC.LIST_ROLES),
  login: (input: LoginInput): Promise<IpcResult<LoginResult>> => ipcRenderer.invoke(IPC.LOGIN, input),
  changePassword: (input: ChangePasswordInput): Promise<IpcResult<SessionInfo>> =>
    ipcRenderer.invoke(IPC.CHANGE_PASSWORD, input),
  resetPassword: (input: ResetPasswordInput): Promise<IpcResult<SessionInfo>> =>
    ipcRenderer.invoke(IPC.RESET_PASSWORD, input),
  adminResetPassword: (input: AdminResetPasswordInput): Promise<IpcResult<AdminResetPasswordResult>> =>
    ipcRenderer.invoke(IPC.ADMIN_RESET_PASSWORD, input),
  logout: (): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.LOGOUT),
  getSession: (): Promise<IpcResult<SessionInfo | null>> => ipcRenderer.invoke(IPC.GET_SESSION),
  listAccountGroups: (): Promise<IpcResult<AccountGroupSummary[]>> => ipcRenderer.invoke(IPC.LIST_ACCOUNT_GROUPS),
  listLedgers: (): Promise<IpcResult<LedgerAccountSummary[]>> => ipcRenderer.invoke(IPC.LIST_LEDGERS),
  createLedger: (input: CreateLedgerInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_LEDGER, input),
  createVoucher: (input: CreateVoucherInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_VOUCHER, input),
  listVouchers: (): Promise<IpcResult<VoucherSummary[]>> => ipcRenderer.invoke(IPC.LIST_VOUCHERS),
  cancelVoucher: (voucherId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CANCEL_VOUCHER, voucherId),
  getTrialBalance: (): Promise<IpcResult<TrialBalanceResult>> => ipcRenderer.invoke(IPC.GET_TRIAL_BALANCE),
  getProfitAndLoss: (input: ProfitAndLossInput): Promise<IpcResult<ProfitAndLossResult>> =>
    ipcRenderer.invoke(IPC.GET_PROFIT_AND_LOSS, input),
  getBalanceSheet: (asOfDate: string): Promise<IpcResult<BalanceSheetResult>> =>
    ipcRenderer.invoke(IPC.GET_BALANCE_SHEET, asOfDate),
  createParty: (input: CreatePartyInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PARTY, input),
  listParties: (): Promise<IpcResult<PartySummary[]>> => ipcRenderer.invoke(IPC.LIST_PARTIES),
  updateBusinessPartyAddress: (input: UpdateBusinessPartyAddressInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_BUSINESS_PARTY_ADDRESS, input),
  createSalesInvoice: (input: CreateSalesInvoiceInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_SALES_INVOICE, input),
  listSalesInvoices: (): Promise<IpcResult<InvoiceSummary[]>> => ipcRenderer.invoke(IPC.LIST_SALES_INVOICES),
  cancelSalesInvoice: (invoiceId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CANCEL_SALES_INVOICE, invoiceId),
  createPurchaseInvoice: (input: CreatePurchaseInvoiceInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PURCHASE_INVOICE, input),
  listPurchaseInvoices: (): Promise<IpcResult<PurchaseInvoiceSummary[]>> => ipcRenderer.invoke(IPC.LIST_PURCHASE_INVOICES),
  cancelPurchaseInvoice: (invoiceId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CANCEL_PURCHASE_INVOICE, invoiceId),
  createSalesOrder: (input: CreateSalesOrderInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_SALES_ORDER, input),
  listSalesOrders: (): Promise<IpcResult<OrderSummary[]>> => ipcRenderer.invoke(IPC.LIST_SALES_ORDERS),
  confirmSalesOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CONFIRM_SALES_ORDER, orderId),
  cancelSalesOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CANCEL_SALES_ORDER, orderId),
  convertSalesOrder: (orderId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CONVERT_SALES_ORDER, orderId),
  createPurchaseOrder: (input: CreatePurchaseOrderInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PURCHASE_ORDER, input),
  listPurchaseOrders: (): Promise<IpcResult<OrderSummary[]>> => ipcRenderer.invoke(IPC.LIST_PURCHASE_ORDERS),
  confirmPurchaseOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CONFIRM_PURCHASE_ORDER, orderId),
  cancelPurchaseOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CANCEL_PURCHASE_ORDER, orderId),
  convertPurchaseOrder: (orderId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CONVERT_PURCHASE_ORDER, orderId),
  listReceivables: (): Promise<IpcResult<PartyOutstandingRow[]>> => ipcRenderer.invoke(IPC.LIST_RECEIVABLES),
  listPayables: (): Promise<IpcResult<PartyOutstandingRow[]>> => ipcRenderer.invoke(IPC.LIST_PAYABLES),
  listMsmeAgeing: (asOfDate: string): Promise<IpcResult<MsmeAgeingRow[]>> => ipcRenderer.invoke(IPC.LIST_MSME_AGEING, asOfDate),
  listOutstandingSalesInvoices: (partyId: string): Promise<IpcResult<OutstandingInvoiceRow[]>> => ipcRenderer.invoke(IPC.LIST_OUTSTANDING_SALES_INVOICES, partyId),
  listOutstandingPurchaseInvoices: (partyId: string): Promise<IpcResult<OutstandingInvoiceRow[]>> => ipcRenderer.invoke(IPC.LIST_OUTSTANDING_PURCHASE_INVOICES, partyId),
  recordSalesReceipt: (input: RecordSalesReceiptInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RECORD_SALES_RECEIPT, input),
  recordPurchasePayment: (input: RecordPurchasePaymentInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RECORD_PURCHASE_PAYMENT, input),
  getThemePreference: (): Promise<IpcResult<ThemePreference>> => ipcRenderer.invoke(IPC.GET_THEME_PREFERENCE),
  setThemePreference: (theme: ThemePreference): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.SET_THEME_PREFERENCE, theme),
  backupCompany: (): Promise<IpcResult<string | null>> => ipcRenderer.invoke(IPC.BACKUP_COMPANY),
  restoreCompany: (): Promise<IpcResult<RestoreResult>> => ipcRenderer.invoke(IPC.RESTORE_COMPANY),
  getLicenseStatus: (): Promise<IpcResult<LicenseStatus>> => ipcRenderer.invoke(IPC.GET_LICENSE_STATUS),
  activateLicenseOnline: (activationCode: string): Promise<IpcResult<LicenseStatus>> => ipcRenderer.invoke(IPC.ACTIVATE_LICENSE_ONLINE, activationCode),
  activateLicense: (activationToken: string): Promise<IpcResult<LicenseStatus>> => ipcRenderer.invoke(IPC.ACTIVATE_LICENSE, activationToken),
  recheckLicense: (): Promise<IpcResult<LicenseStatus>> => ipcRenderer.invoke(IPC.RECHECK_LICENSE),
  getMachineId: (): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.GET_MACHINE_ID),
  getTrialStatus: (): Promise<IpcResult<TrialStatus>> => ipcRenderer.invoke(IPC.GET_TRIAL_STATUS),
  createDemoCompany: (): Promise<IpcResult<SessionInfo>> => ipcRenderer.invoke(IPC.CREATE_DEMO_COMPANY),
  listAllPermissions: (): Promise<IpcResult<PermissionSummary[]>> => ipcRenderer.invoke(IPC.LIST_ALL_PERMISSIONS),
  listRolesWithPermissions: (): Promise<IpcResult<RoleWithPermissionsSummary[]>> => ipcRenderer.invoke(IPC.LIST_ROLES_WITH_PERMISSIONS),
  createRole: (input: CreateRoleInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_ROLE, input),
  updateRolePermissions: (input: UpdateRolePermissionsInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_ROLE_PERMISSIONS, input),
  createUnitOfMeasure: (input: CreateUnitOfMeasureInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_UNIT_OF_MEASURE, input),
  listUnitsOfMeasure: (): Promise<IpcResult<UnitOfMeasureSummary[]>> => ipcRenderer.invoke(IPC.LIST_UNITS_OF_MEASURE),
  createWarehouse: (input: CreateWarehouseInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_WAREHOUSE, input),
  listWarehouses: (): Promise<IpcResult<WarehouseSummary[]>> => ipcRenderer.invoke(IPC.LIST_WAREHOUSES),
  createItem: (input: CreateItemInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_ITEM, input),
  listItems: (): Promise<IpcResult<ItemSummary[]>> => ipcRenderer.invoke(IPC.LIST_ITEMS),
  listBatchesForItem: (itemId: string): Promise<IpcResult<ItemBatchSummary[]>> => ipcRenderer.invoke(IPC.LIST_BATCHES_FOR_ITEM, itemId),
  recordOpeningStock: (input: RecordOpeningStockInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RECORD_OPENING_STOCK, input),
  postStockAdjustment: (input: PostStockAdjustmentInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.POST_STOCK_ADJUSTMENT, input),
  cancelStockAdjustment: (voucherId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CANCEL_STOCK_ADJUSTMENT, voucherId),
  transferStock: (input: TransferStockInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.TRANSFER_STOCK, input),
  listStockMovements: (): Promise<IpcResult<StockMovementSummary[]>> => ipcRenderer.invoke(IPC.LIST_STOCK_MOVEMENTS),
  getStockPosition: (query: StockPositionQuery): Promise<IpcResult<StockPositionRow[]>> => ipcRenderer.invoke(IPC.GET_STOCK_POSITION, query),
  createOrUpdateGstRate: (input: CreateOrUpdateGstRateInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_OR_UPDATE_GST_RATE, input),
  listGstRates: (hsnSacCode: string): Promise<IpcResult<GstRateVersion[]>> => ipcRenderer.invoke(IPC.LIST_GST_RATES, hsnSacCode),
  listActiveGstRates: (): Promise<IpcResult<GstRateSummary[]>> => ipcRenderer.invoke(IPC.LIST_ACTIVE_GST_RATES),
  previewGst: (input: GstRatePreviewInput): Promise<IpcResult<GstRatePreviewResult>> => ipcRenderer.invoke(IPC.PREVIEW_GST, input),
  getGstSummary: (input: GstSummaryInput): Promise<IpcResult<GstSummaryResult>> => ipcRenderer.invoke(IPC.GET_GST_SUMMARY, input),
  getGstr1: (input: GstReturnPeriodInput): Promise<IpcResult<Gstr1Result>> => ipcRenderer.invoke(IPC.GET_GSTR1, input),
  getGstr3b: (input: GstReturnPeriodInput): Promise<IpcResult<Gstr3bResult>> => ipcRenderer.invoke(IPC.GET_GSTR3B, input),
  getGstr9: (input: GstFinancialYearInput): Promise<IpcResult<Gstr9Result>> => ipcRenderer.invoke(IPC.GET_GSTR9, input),
  getGstr9c: (input: GstFinancialYearInput): Promise<IpcResult<Gstr9cResult>> => ipcRenderer.invoke(IPC.GET_GSTR9C, input),
  exportCsv: (input: ExportCsvInput): Promise<IpcResult<boolean>> => ipcRenderer.invoke(IPC.EXPORT_CSV, input),
  listBankAccounts: (): Promise<IpcResult<BankAccountSummary[]>> => ipcRenderer.invoke(IPC.LIST_BANK_ACCOUNTS),
  createBankAccount: (input: CreateBankAccountInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_BANK_ACCOUNT, input),
  recordBankVoucher: (input: RecordBankVoucherInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RECORD_BANK_VOUCHER, input),
  updateInstrumentStatus: (input: UpdateInstrumentStatusInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_INSTRUMENT_STATUS, input),
  listPaymentInstruments: (status?: InstrumentStatus): Promise<IpcResult<PaymentInstrumentSummary[]>> => ipcRenderer.invoke(IPC.LIST_PAYMENT_INSTRUMENTS, status),
  listReconcilableLines: (input: ListReconcilableLinesInput): Promise<IpcResult<ReconcilableLineRow[]>> => ipcRenderer.invoke(IPC.LIST_RECONCILABLE_LINES, input),
  markLineReconciled: (input: MarkReconciledInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.MARK_LINE_RECONCILED, input),
  markLineUnreconciled: (voucherLineId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.MARK_LINE_UNRECONCILED, voucherLineId),
  getReconciliationStatement: (input: GetReconciliationStatementInput): Promise<IpcResult<BankReconciliationStatement>> => ipcRenderer.invoke(IPC.GET_RECONCILIATION_STATEMENT, input),
  pickStatementFile: (): Promise<IpcResult<{ fileName: string; csvText: string } | null>> => ipcRenderer.invoke(IPC.PICK_STATEMENT_FILE),
  previewStatementCsv: (csvText: string): Promise<IpcResult<StatementPreview>> => ipcRenderer.invoke(IPC.PREVIEW_STATEMENT_CSV, csvText),
  importStatementFile: (input: ImportStatementFileInput): Promise<IpcResult<ImportStatementResult>> => ipcRenderer.invoke(IPC.IMPORT_STATEMENT_FILE, input),
  listStatementImports: (bankAccountId: string): Promise<IpcResult<StatementImportSummary[]>> => ipcRenderer.invoke(IPC.LIST_STATEMENT_IMPORTS, bankAccountId),
  getStatementImportLines: (importId: string): Promise<IpcResult<StatementLineSummary[]>> => ipcRenderer.invoke(IPC.GET_STATEMENT_IMPORT_LINES, importId),
  resolveStatementLineMatch: (input: ResolveStatementLineMatchInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.RESOLVE_STATEMENT_LINE_MATCH, input),
  listEmployees: (): Promise<IpcResult<EmployeeSummary[]>> => ipcRenderer.invoke(IPC.LIST_EMPLOYEES),
  createEmployee: (input: CreateEmployeeInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_EMPLOYEE, input),
  listExpenseClaims: (): Promise<IpcResult<ExpenseClaimSummary[]>> => ipcRenderer.invoke(IPC.LIST_EXPENSE_CLAIMS),
  createExpenseClaim: (input: CreateExpenseClaimInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_EXPENSE_CLAIM, input),
  submitExpenseClaim: (expenseClaimId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.SUBMIT_EXPENSE_CLAIM, expenseClaimId),
  approveExpenseClaim: (expenseClaimId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.APPROVE_EXPENSE_CLAIM, expenseClaimId),
  rejectExpenseClaim: (input: RejectExpenseClaimInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.REJECT_EXPENSE_CLAIM, input),
  cancelExpenseClaim: (expenseClaimId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CANCEL_EXPENSE_CLAIM, expenseClaimId),
  reimburseExpenseClaim: (input: ReimburseExpenseClaimInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.REIMBURSE_EXPENSE_CLAIM, input),
  listOutstandingReimbursements: (employeeId?: string): Promise<IpcResult<OutstandingReimbursementRow[]>> => ipcRenderer.invoke(IPC.LIST_OUTSTANDING_REIMBURSEMENTS, employeeId),
  pickAttachmentFile: (): Promise<IpcResult<{ fileName: string; mimeType: string; fileDataBase64: string } | null>> => ipcRenderer.invoke(IPC.PICK_ATTACHMENT_FILE),
  uploadDocument: (input: UploadDocumentInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.UPLOAD_DOCUMENT, input),
  listDocumentsForEntity: (input: ListDocumentsForEntityInput): Promise<IpcResult<DocumentSummary[]>> => ipcRenderer.invoke(IPC.LIST_DOCUMENTS_FOR_ENTITY, input),
  downloadDocument: (documentId: string): Promise<IpcResult<DownloadDocumentResult>> => ipcRenderer.invoke(IPC.DOWNLOAD_DOCUMENT, documentId),
  deleteDocument: (documentId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.DELETE_DOCUMENT, documentId),
  searchDocuments: (input: SearchDocumentsInput): Promise<IpcResult<DocumentSummary[]>> => ipcRenderer.invoke(IPC.SEARCH_DOCUMENTS, input),

  listEmployeePayrollProfiles: (): Promise<IpcResult<EmployeePayrollProfileSummary[]>> => ipcRenderer.invoke(IPC.LIST_EMPLOYEE_PAYROLL_PROFILES),
  updateEmployeePayrollProfile: (input: UpdateEmployeePayrollProfileInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_EMPLOYEE_PAYROLL_PROFILE, input),
  createSalaryComponent: (input: SalaryComponentDefinitionInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_SALARY_COMPONENT, input),
  listSalaryComponents: (): Promise<IpcResult<SalaryComponentDefinitionSummary[]>> => ipcRenderer.invoke(IPC.LIST_SALARY_COMPONENTS),
  assignSalaryStructure: (input: AssignSalaryStructureInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.ASSIGN_SALARY_STRUCTURE, input),
  listSalaryStructuresForEmployee: (employeeId: string): Promise<IpcResult<SalaryStructureSummary[]>> => ipcRenderer.invoke(IPC.LIST_SALARY_STRUCTURES_FOR_EMPLOYEE, employeeId),
  getCompanyPayrollSettings: (): Promise<IpcResult<CompanyPayrollSettingsSummary>> => ipcRenderer.invoke(IPC.GET_COMPANY_PAYROLL_SETTINGS),
  updateCompanyPayrollSettings: (input: UpdateCompanyPayrollSettingsInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_COMPANY_PAYROLL_SETTINGS, input),
  createOrUpdatePayrollRule: (input: CreateOrUpdatePayrollRuleInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_OR_UPDATE_PAYROLL_RULE, input),
  listActivePayrollRules: (): Promise<IpcResult<PayrollRuleVersionSummary[]>> => ipcRenderer.invoke(IPC.LIST_ACTIVE_PAYROLL_RULES),
  listPayrollRuleVersions: (ruleType: string): Promise<IpcResult<PayrollRuleVersionSummary[]>> => ipcRenderer.invoke(IPC.LIST_PAYROLL_RULE_VERSIONS, ruleType),
  createLeaveType: (input: LeaveTypeInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_LEAVE_TYPE, input),
  listLeaveTypes: (): Promise<IpcResult<LeaveTypeSummary[]>> => ipcRenderer.invoke(IPC.LIST_LEAVE_TYPES),
  applyLeave: (input: ApplyLeaveInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.APPLY_LEAVE, input),
  listLeaveApplications: (employeeId?: string): Promise<IpcResult<LeaveApplicationSummary[]>> => ipcRenderer.invoke(IPC.LIST_LEAVE_APPLICATIONS, employeeId),
  approveLeave: (leaveApplicationId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.APPROVE_LEAVE, leaveApplicationId),
  rejectLeave: (input: RejectLeaveInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.REJECT_LEAVE, input),
  listLeaveBalances: (employeeId: string): Promise<IpcResult<LeaveBalanceSummary[]>> => ipcRenderer.invoke(IPC.LIST_LEAVE_BALANCES, employeeId),
  markAttendance: (input: MarkAttendanceInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.MARK_ATTENDANCE, input),
  listAttendanceForEmployee: (input: ListAttendanceForEmployeeInput): Promise<IpcResult<AttendanceRecordSummary[]>> => ipcRenderer.invoke(IPC.LIST_ATTENDANCE_FOR_EMPLOYEE, input),
  createPayrollRun: (input: CreatePayrollRunInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PAYROLL_RUN, input),
  processPayrollRun: (payrollRunId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.PROCESS_PAYROLL_RUN, payrollRunId),
  overridePayslipTds: (input: OverridePayslipTdsInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.OVERRIDE_PAYSLIP_TDS, input),
  getPayrollRun: (payrollRunId: string): Promise<IpcResult<PayrollRunSummary>> => ipcRenderer.invoke(IPC.GET_PAYROLL_RUN, payrollRunId),
  listPayrollRuns: (): Promise<IpcResult<PayrollRunSummary[]>> => ipcRenderer.invoke(IPC.LIST_PAYROLL_RUNS),
  postPayrollRun: (payrollRunId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.POST_PAYROLL_RUN, payrollRunId),
  disbursePayslip: (input: DisbursePayslipInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.DISBURSE_PAYSLIP, input),
  runGratuityProvisioning: (input: RunGratuityProvisioningInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RUN_GRATUITY_PROVISIONING, input),
  recordSeparation: (input: RecordSeparationInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RECORD_SEPARATION, input),
  settleGratuity: (input: SettleGratuityInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.SETTLE_GRATUITY, input),
  listGratuityRecords: (): Promise<IpcResult<GratuityRecordSummary[]>> => ipcRenderer.invoke(IPC.LIST_GRATUITY_RECORDS),

  createCostCentre: (input: CreateCostCentreInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_COST_CENTRE, input),
  listCostCentres: (): Promise<IpcResult<CostCentreSummary[]>> => ipcRenderer.invoke(IPC.LIST_COST_CENTRES),
  updateCostCentre: (input: UpdateCostCentreInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_COST_CENTRE, input),
  getCostCentreReport: (input: CostCentreReportInput): Promise<IpcResult<CostCentreSummaryRow[]>> => ipcRenderer.invoke(IPC.GET_COST_CENTRE_REPORT, input),
  createBudget: (input: CreateBudgetInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_BUDGET, input),
  listBudgets: (): Promise<IpcResult<BudgetSummary[]>> => ipcRenderer.invoke(IPC.LIST_BUDGETS),
  updateBudgetLine: (input: UpdateBudgetLineInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_BUDGET_LINE, input),
  getBudgetVsActual: (budgetId: string): Promise<IpcResult<BudgetVsActualResult>> => ipcRenderer.invoke(IPC.GET_BUDGET_VS_ACTUAL, budgetId),
  createAssetClass: (input: CreateAssetClassInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_ASSET_CLASS, input),
  listAssetClasses: (): Promise<IpcResult<AssetClassSummary[]>> => ipcRenderer.invoke(IPC.LIST_ASSET_CLASSES),
  acquireFixedAsset: (input: AcquireFixedAssetInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.ACQUIRE_FIXED_ASSET, input),
  listFixedAssets: (): Promise<IpcResult<FixedAssetSummary[]>> => ipcRenderer.invoke(IPC.LIST_FIXED_ASSETS),
  getAssetDepreciationSchedule: (assetId: string): Promise<IpcResult<AssetDepreciationEntrySummary[]>> => ipcRenderer.invoke(IPC.GET_ASSET_DEPRECIATION_SCHEDULE, assetId),
  disposeFixedAsset: (input: DisposeFixedAssetInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.DISPOSE_FIXED_ASSET, input),
  previewDepreciationRun: (input: RunDepreciationInput): Promise<IpcResult<DepreciationPreviewLine[]>> => ipcRenderer.invoke(IPC.PREVIEW_DEPRECIATION_RUN, input),
  postDepreciationRun: (input: RunDepreciationInput): Promise<IpcResult<PostDepreciationResult>> => ipcRenderer.invoke(IPC.POST_DEPRECIATION_RUN, input),
  createOrUpdateFixedAssetRate: (input: CreateOrUpdateFixedAssetRateInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_OR_UPDATE_FIXED_ASSET_RATE, input),
  listActiveFixedAssetRates: (): Promise<IpcResult<FixedAssetRateVersionSummary[]>> => ipcRenderer.invoke(IPC.LIST_ACTIVE_FIXED_ASSET_RATES),
  listFixedAssetRateVersions: (ruleType: string): Promise<IpcResult<FixedAssetRateVersionSummary[]>> => ipcRenderer.invoke(IPC.LIST_FIXED_ASSET_RATE_VERSIONS, ruleType),

  createBranch: (input: CreateBranchInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_BRANCH, input),
  listBranches: (): Promise<IpcResult<BranchSummary[]>> => ipcRenderer.invoke(IPC.LIST_BRANCHES),
  updateBranch: (input: UpdateBranchInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_BRANCH, input),
  recordInterBranchTransfer: (input: RecordInterBranchTransferInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.RECORD_INTER_BRANCH_TRANSFER, input),
  getBranchProfitAndLoss: (input: BranchReportInput): Promise<IpcResult<BranchProfitAndLossRow[]>> => ipcRenderer.invoke(IPC.GET_BRANCH_PROFIT_AND_LOSS, input),
  getBranchBalanceSheet: (asOfDate: string): Promise<IpcResult<BranchBalanceSheetResult>> => ipcRenderer.invoke(IPC.GET_BRANCH_BALANCE_SHEET, asOfDate),
  setExchangeRate: (input: SetExchangeRateInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.SET_EXCHANGE_RATE, input),
  listActiveExchangeRates: (): Promise<IpcResult<ExchangeRateVersionSummary[]>> => ipcRenderer.invoke(IPC.LIST_ACTIVE_EXCHANGE_RATES),
  listExchangeRateVersions: (currency: string): Promise<IpcResult<ExchangeRateVersionSummary[]>> => ipcRenderer.invoke(IPC.LIST_EXCHANGE_RATE_VERSIONS, currency),
  previewFxRevaluation: (input: RunFxRevaluationInput): Promise<IpcResult<FxRevaluationPreviewResult>> => ipcRenderer.invoke(IPC.PREVIEW_FX_REVALUATION, input),
  postFxRevaluation: (input: RunFxRevaluationInput): Promise<IpcResult<FxRevaluationRunResult>> => ipcRenderer.invoke(IPC.POST_FX_REVALUATION, input),
  listFxRevaluationRuns: (): Promise<IpcResult<{ id: string; runDate: string; financialYear: string; voucherId: string | null }[]>> => ipcRenderer.invoke(IPC.LIST_FX_REVALUATION_RUNS),

  createBillOfMaterial: (input: CreateBillOfMaterialInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_BILL_OF_MATERIAL, input),
  listBillsOfMaterial: (): Promise<IpcResult<BillOfMaterialSummary[]>> => ipcRenderer.invoke(IPC.LIST_BILLS_OF_MATERIAL),
  postManufacturingJournal: (input: PostManufacturingJournalInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.POST_MANUFACTURING_JOURNAL, input),
  listManufacturingJournals: (): Promise<IpcResult<ManufacturingJournalSummary[]>> => ipcRenderer.invoke(IPC.LIST_MANUFACTURING_JOURNALS),
  getManufacturingJournalMovements: (journalId: string): Promise<IpcResult<ManufacturingJournalMovementSummary[]>> => ipcRenderer.invoke(IPC.GET_MANUFACTURING_JOURNAL_MOVEMENTS, journalId),

  getCompanyLetterheadProfile: (): Promise<IpcResult<CompanyLetterheadProfile>> => ipcRenderer.invoke(IPC.GET_COMPANY_LETTERHEAD_PROFILE),
  updateCompanyLetterheadProfile: (input: UpdateCompanyLetterheadProfileInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPDATE_COMPANY_LETTERHEAD_PROFILE, input),
  pickLogoFile: (): Promise<IpcResult<PickedLogoFile | null>> => ipcRenderer.invoke(IPC.PICK_LOGO_FILE),
  uploadCompanyLogo: (input: UploadCompanyLogoInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.UPLOAD_COMPANY_LOGO, input),
  clearCompanyLogo: (): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CLEAR_COMPANY_LOGO),
  printSalesInvoice: (invoiceId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.PRINT_SALES_INVOICE, invoiceId),
  saveSalesInvoicePdf: (invoiceId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.SAVE_SALES_INVOICE_PDF, invoiceId),
  printPayslip: (payslipId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.PRINT_PAYSLIP, payslipId),
  savePayslipPdf: (payslipId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.SAVE_PAYSLIP_PDF, payslipId),
  printPurchaseInvoice: (invoiceId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.PRINT_PURCHASE_INVOICE, invoiceId),
  savePurchaseInvoicePdf: (invoiceId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.SAVE_PURCHASE_INVOICE_PDF, invoiceId),
  printSalesOrder: (orderId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.PRINT_SALES_ORDER, orderId),
  saveSalesOrderPdf: (orderId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.SAVE_SALES_ORDER_PDF, orderId),
  printPurchaseOrder: (orderId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.PRINT_PURCHASE_ORDER, orderId),
  savePurchaseOrderPdf: (orderId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.SAVE_PURCHASE_ORDER_PDF, orderId),
  printVoucher: (voucherId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.PRINT_VOUCHER, voucherId),
  saveVoucherPdf: (voucherId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.SAVE_VOUCHER_PDF, voucherId),
  printExpenseClaim: (expenseClaimId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.PRINT_EXPENSE_CLAIM, expenseClaimId),
  saveExpenseClaimPdf: (expenseClaimId: string): Promise<IpcResult<PrintDocumentResult>> => ipcRenderer.invoke(IPC.SAVE_EXPENSE_CLAIM_PDF, expenseClaimId),
  listPayslipsForPrint: (): Promise<IpcResult<PayslipPrintListItem[]>> => ipcRenderer.invoke(IPC.LIST_PAYSLIPS_FOR_PRINT),
  getTemplateLayout: (documentFamily: TemplateFamily): Promise<IpcResult<PrintTemplateLayoutSummary | null>> => ipcRenderer.invoke(IPC.GET_TEMPLATE_LAYOUT, documentFamily),
  saveTemplateLayout: (input: SaveTemplateLayoutInput): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.SAVE_TEMPLATE_LAYOUT, input),
  revertTemplateLayout: (documentFamily: TemplateFamily): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.REVERT_TEMPLATE_LAYOUT, documentFamily),
  listTemplateLayoutVersions: (documentFamily: TemplateFamily): Promise<IpcResult<PrintTemplateLayoutSummary[]>> => ipcRenderer.invoke(IPC.LIST_TEMPLATE_LAYOUT_VERSIONS, documentFamily),
  getTemplatePreviewData: (documentFamily: TemplateFamily): Promise<IpcResult<TemplatePreviewData>> => ipcRenderer.invoke(IPC.GET_TEMPLATE_PREVIEW_DATA, documentFamily),
  getTemplateFieldCatalog: (documentFamily: TemplateFamily): Promise<IpcResult<TemplateFieldCatalogEntry[]>> => ipcRenderer.invoke(IPC.GET_TEMPLATE_FIELD_CATALOG, documentFamily),

  checkForUpdate: (): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CHECK_FOR_UPDATE),
  quitAndInstall: (): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.QUIT_AND_INSTALL),
  /** Push subscription (not request/response) — returns an unsubscribe function for a React effect's cleanup. */
  onUpdateStatus: (callback: (status: UpdateStatus) => void): (() => void) => {
    const listener = (_event: Electron.IpcRendererEvent, status: UpdateStatus) => callback(status);
    ipcRenderer.on(UPDATE_STATUS_EVENT, listener);
    return () => ipcRenderer.removeListener(UPDATE_STATUS_EVENT, listener);
  },

  verifyAuditTrail: (): Promise<IpcResult<AuditChainVerificationResult>> => ipcRenderer.invoke(IPC.VERIFY_AUDIT_TRAIL),
};

export type MhtsApi = typeof api;

contextBridge.exposeInMainWorld('mhts', api);
