import { contextBridge, ipcRenderer } from 'electron';
import {
  IPC,
  type AccountGroupSummary,
  type AdminResetPasswordInput,
  type AdminResetPasswordResult,
  type BalanceSheetResult,
  type ChangePasswordInput,
  type CompanySummary,
  type CompanyUserSummary,
  type CreateCompanyInput,
  type CreateCompanyResult,
  type CreateLedgerInput,
  type CreatePartyInput,
  type CreatePurchaseInvoiceInput,
  type CreatePurchaseOrderInput,
  type CreateSalesInvoiceInput,
  type CreateSalesOrderInput,
  type CreateVoucherInput,
  type InvoiceSummary,
  type IpcResult,
  type LedgerAccountSummary,
  type LoginInput,
  type LoginResult,
  type MsmeAgeingRow,
  type OrderSummary,
  type PartyOutstandingRow,
  type PartySummary,
  type ProfitAndLossInput,
  type ProfitAndLossResult,
  type PurchaseInvoiceSummary,
  type ResetPasswordInput,
  type SessionInfo,
  type TrialBalanceResult,
  type VoucherSummary,
} from '../shared/ipc';

const api = {
  listCompanies: (): Promise<IpcResult<CompanySummary[]>> => ipcRenderer.invoke(IPC.LIST_COMPANIES),
  createCompany: (input: CreateCompanyInput): Promise<IpcResult<CreateCompanyResult>> =>
    ipcRenderer.invoke(IPC.CREATE_COMPANY, input),
  listCompanyUsers: (): Promise<IpcResult<CompanyUserSummary[]>> => ipcRenderer.invoke(IPC.LIST_COMPANY_USERS),
  login: (input: LoginInput): Promise<IpcResult<LoginResult>> => ipcRenderer.invoke(IPC.LOGIN, input),
  changePassword: (input: ChangePasswordInput): Promise<IpcResult<SessionInfo>> =>
    ipcRenderer.invoke(IPC.CHANGE_PASSWORD, input),
  resetPassword: (input: ResetPasswordInput): Promise<IpcResult<SessionInfo>> =>
    ipcRenderer.invoke(IPC.RESET_PASSWORD, input),
  adminResetPassword: (input: AdminResetPasswordInput): Promise<IpcResult<AdminResetPasswordResult>> =>
    ipcRenderer.invoke(IPC.ADMIN_RESET_PASSWORD, input),
  logout: (): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.LOGOUT),
  getSession: (): Promise<IpcResult<SessionInfo | null>> => ipcRenderer.invoke(IPC.GET_SESSION),
  listAccountGroups: (): Promise<IpcResult<AccountGroupSummary[]>> => ipcRenderer.invoke(IPC.LIST_ACCOUNT_GROUPS),
  listLedgers: (): Promise<IpcResult<LedgerAccountSummary[]>> => ipcRenderer.invoke(IPC.LIST_LEDGERS),
  createLedger: (input: CreateLedgerInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_LEDGER, input),
  createVoucher: (input: CreateVoucherInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_VOUCHER, input),
  listVouchers: (): Promise<IpcResult<VoucherSummary[]>> => ipcRenderer.invoke(IPC.LIST_VOUCHERS),
  cancelVoucher: (voucherId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CANCEL_VOUCHER, voucherId),
  getTrialBalance: (): Promise<IpcResult<TrialBalanceResult>> => ipcRenderer.invoke(IPC.GET_TRIAL_BALANCE),
  getProfitAndLoss: (input: ProfitAndLossInput): Promise<IpcResult<ProfitAndLossResult>> =>
    ipcRenderer.invoke(IPC.GET_PROFIT_AND_LOSS, input),
  getBalanceSheet: (asOfDate: string): Promise<IpcResult<BalanceSheetResult>> =>
    ipcRenderer.invoke(IPC.GET_BALANCE_SHEET, asOfDate),
  createParty: (input: CreatePartyInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PARTY, input),
  listParties: (): Promise<IpcResult<PartySummary[]>> => ipcRenderer.invoke(IPC.LIST_PARTIES),
  createSalesInvoice: (input: CreateSalesInvoiceInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_SALES_INVOICE, input),
  listSalesInvoices: (): Promise<IpcResult<InvoiceSummary[]>> => ipcRenderer.invoke(IPC.LIST_SALES_INVOICES),
  createPurchaseInvoice: (input: CreatePurchaseInvoiceInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PURCHASE_INVOICE, input),
  listPurchaseInvoices: (): Promise<IpcResult<PurchaseInvoiceSummary[]>> => ipcRenderer.invoke(IPC.LIST_PURCHASE_INVOICES),
  createSalesOrder: (input: CreateSalesOrderInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_SALES_ORDER, input),
  listSalesOrders: (): Promise<IpcResult<OrderSummary[]>> => ipcRenderer.invoke(IPC.LIST_SALES_ORDERS),
  confirmSalesOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CONFIRM_SALES_ORDER, orderId),
  cancelSalesOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CANCEL_SALES_ORDER, orderId),
  convertSalesOrder: (orderId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CONVERT_SALES_ORDER, orderId),
  createPurchaseOrder: (input: CreatePurchaseOrderInput): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CREATE_PURCHASE_ORDER, input),
  listPurchaseOrders: (): Promise<IpcResult<OrderSummary[]>> => ipcRenderer.invoke(IPC.LIST_PURCHASE_ORDERS),
  confirmPurchaseOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CONFIRM_PURCHASE_ORDER, orderId),
  cancelPurchaseOrder: (orderId: string): Promise<IpcResult<void>> => ipcRenderer.invoke(IPC.CANCEL_PURCHASE_ORDER, orderId),
  convertPurchaseOrder: (orderId: string): Promise<IpcResult<string>> => ipcRenderer.invoke(IPC.CONVERT_PURCHASE_ORDER, orderId),
  listReceivables: (): Promise<IpcResult<PartyOutstandingRow[]>> => ipcRenderer.invoke(IPC.LIST_RECEIVABLES),
  listPayables: (): Promise<IpcResult<PartyOutstandingRow[]>> => ipcRenderer.invoke(IPC.LIST_PAYABLES),
  listMsmeAgeing: (asOfDate: string): Promise<IpcResult<MsmeAgeingRow[]>> => ipcRenderer.invoke(IPC.LIST_MSME_AGEING, asOfDate),
};

export type MhtsApi = typeof api;

contextBridge.exposeInMainWorld('mhts', api);
